name: 'Terraform'

on: [push, pull_request]

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./infra

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.10

    - name: Terraform Init
      id: init
      env:
        TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      run: terraform init

    - name: Terraform Plan
      id: plan
      env:
        TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color

    - name: Add Plan Comment
      id: comment
      uses: actions/github-script@v3
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Init ⚙️ \`${{ steps.init.outcome }}\`
          #### Terraform Plan 📖 \`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`${process.env.PLAN}\`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Branch: \`${{ github.ref }}\`*`;
          
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      env:
        TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      run: terraform apply -auto-approve
